### ISSUE TITLE
Incorrect background shorthand handling

### ISSUE THREAD

**Issue by breeswish** [jakubpawlowicz/clean-css#808] opened 2016-09-07 03:11 UTC
When there are no spaces between `)` and `url` (usually generated by another css minifier), `clean-css` will break:

``` css
.a{background:rgba(0,0,0,0)url(//example.com/a.jpg)}
```

Minified:

``` css
.a{background:0 0}
```

**Comment by jakubpawlowicz** [comment] 2016-09-07 05:41
Looks like a bug in advanced optimizations, as it works OK with `--skip-advanced` flag.

**Comment by jakubpawlowicz** [comment] 2016-12-23 21:04
Already fixed on master thanks to the new tokenizer. Added a test case to prevent regressions.

**Closed by jakubpawlowicz** 2016-12-23 21:04 UTC
Labels: Bug
