### ISSUE TITLE
Breaking border-color in ie up to 11

### ISSUE THREAD

**Issue by d4rkr00t** [jakubpawlowicz/clean-css#578] opened 2015-05-20 11:35 UTC
clean-css has `-c` option intended to handle ie7-8 issues, but there is an issue with all latest ie, and mobile ie:

This code:
```css
.b:before
{
    border-color: rgba(0,0,0,.2) rgba(0,0,0,.1) rgba(0,0,0,.2) rgba(0,0,0,.1);
}

```

Will be minimized to:
```css
.b:before{border-color:rgba(0,0,0,.2)rgba(0,0,0,.1)}
```

Which doesn't work in all ie up to 11. With `-c ie8` option everything works as expected, produced code will be:
```css
.b:before{border-color:rgba(0,0,0,.2) rgba(0,0,0,.1)}
```

With space between rgba and rgba.

May be better not to remove space between rgba in such cases?

**Comment by jakubpawlowicz** [comment] 2015-05-20 12:15
@d4rkr00t it's a duplicate of #542 - already fixed in 3.3-pre / master due to be released as soon as I find some time to finish the changes.

**Closed by jakubpawlowicz** 2015-05-20 12:15 UTC

**Comment by jakubpawlowicz** [comment] 2015-05-20 12:16
Please use `--compatibility +properties.spaceAfterClosingBrace` for now on.

**Comment by d4rkr00t** [comment] 2015-05-20 12:29
Great, thanks!
