### ISSUE TITLE
Multiple input files with imports

### ISSUE THREAD

**Issue by madwizard-thomas** [jakubpawlowicz/clean-css#848] opened 2016-12-21 16:37 UTC
When using multiple input files, an \@import in anything but the first file will be wrongly treated as if after css content (probably because of the concatenation in the source reader). I've tested this in the master branch.

Try this snippet in module-test:
```javascript
new CleanCSS().minify(
          sourcesAsHash([
            'test/fixtures/partials/two.css',
            'test/fixtures/partials-relative/extra/included.css',
            'test/fixtures/129-assets/assets/ui.css'
          ])
```
 It will only output the contents of two.css and ignore the other files with these warnings:
```
Ignoring local @import of "test/fixtures/129-assets/components/bootstrap/css/bootstrap.css" as after other content.
Ignoring local @import of "test/fixtures/129-assets/components/jquery-ui/css/style.css" as after other content.
```

**Comment by jakubpawlowicz** [comment] 2016-12-22 15:15
Duplicate of #801 - moving discussion there.

**Closed by jakubpawlowicz** 2016-12-22 15:15 UTC
