### ISSUE TITLE
"TypeError: Cannot read property '0' of null" when run on invalid input

### ISSUE THREAD

**Issue by GeorgePhillips** [jakubpawlowicz/clean-css#710] opened 2015-11-30 02:37 UTC
The following code:

``` javascript
var content = [".accidental-sass {",
"    color: red;",
"    &:hover {",
"        color: blue;",
"    }",
"}"].join("\n");

var CleanCSS = require("clean-css");

new CleanCSS({processImport: false}).minify(content, function (err, minified) {
    if (err) {
        console.log("CleanCSS error", err);
    } else {
        console.log("CleanCSS success", minified);
    }
}.bind(this));
```

throws the following error:

```
TypeError: Cannot read property '0' of null
    at findNameRoot (node_modules/clean-css/lib/selectors/extractor.js:66:59)
    at extract (node_modules/clean-css/lib/selectors/extractor.js:36:9)
    at restructure (node_modules/clean-css/lib/selectors/restructure.js:288:22)
    at optimize (node_modules/clean-css/lib/selectors/advanced.js:71:5)
    at minify (node_modules/clean-css/lib/clean.js:228:5)
    at whenSourceMapReady (node_modules/clean-css/lib/clean.js:135:7)
    at node_modules/clean-css/lib/clean.js:155:14
    at CleanCSS.minify (node_modules/clean-css/lib/clean.js:127:42)
    at Object.<anonymous> (test.js:13:38)
    at Module._compile (module.js:425:26)
```

This is invalid CSS as it contains SASS style code however it causes an issue when cleaning user generated input. Inside extractor.js it has:

```
  return name.replace(/^\-\w+\-/, '').match(/([a-zA-Z]+)/)[0].toLowerCase();
```

name in the example given is `&` which contains no alpha characters meaning match returns null.

**Comment by alfaproject** [comment] 2015-11-30 08:29
As it should. (;
Like you said, that's invalid CSS.

**Comment by GeorgePhillips** [comment] 2015-11-30 09:42
It should definitely result in an error. I was unclear, the cod throws an error instead of returning it to the callback.

**Comment by jakubpawlowicz** [comment] 2015-12-02 09:47
@GeorgePhillips @alfaproject This is a valid point, as such problems should be caught and reported within `err`. Currently clean-css does not discriminate against unknown CSS properties but it likely will with the next major version. Accepting this issue as an enhancement.

**Comment by shawndumas** [comment] 2016-02-29 18:03
+1 we're being hit by this because of PostCSS's allowance of `&` to refer to the parent selector.

**Comment by jakubpawlowicz** [comment] 2016-12-23 22:04
The current master reports an invalid `&:hover` property, i.e.

```bash
> cat test.css
.accidental-sass {
  color: red;
  &:hover {
    color: blue;
  }
}
> cleancss test.css
WARNING: Invalid property name '&' at test.css:3:2. Ignoring.
.accidental-sass{color:red}
```

And that's how browsers will interpret `&:hover` too.

I've added a test case to prevent regressions and closing it now as it seems good enough. Please comment / reopen if you disagree.

**Closed by jakubpawlowicz** 2016-12-23 22:04 UTC
Labels: Enhancement

**Comment by Prologh** [comment] 2019-04-24 11:37
Just discovered that following code also throws an error _"TypeError: Cannot read property '0' of null" when run on invalid input"_

```css
/*// ' */
a {
  color: black;
  /* &:totally-not-a-css { } */ 
}
```

There are three ways to make it work, though:
 1. Add space between `/*` and `//`, so the top line would be `/* // ' */`;
 2. Remove the apostrophe from the top comment;
 3. Change the `&` sign to something more recognizable in CSS like `a`, so the commented line would look `/* a:totally-not-a-css { } */`.

There are some weird correlations going on causing this error. I tested it the best I could, I leave you with my insight.

Full stack trace:

```
TypeError: Cannot read property '0' of null
    at findNameRoot (\node_modules\clean-css\lib\selectors\extractor.js:66:59)
    at extract (\node_modules\clean-css\lib\selectors\extractor.js:36:9)
    at restructure (\node_modules\clean-css\lib\selectors\restructure.js:297:22)
    at optimize (\node_modules\clean-css\lib\selectors\advanced.js:71:5)
    at recursivelyOptimizeBlocks (\node_modules\clean-css\lib\selectors\advanced.js:40:7)
    at optimize (\node_modules\clean-css\lib\selectors\advanced.js:60:3)
    at minify (\node_modules\clean-css\lib\clean.js:228:5)
    at whenSourceMapReady (\node_modules\clean-css\lib\clean.js:135:7)
    at Object.whenDone (\node_modules\clean-css\lib\clean.js:155:14)
    at processNext (\node_modules\clean-css\lib\imports\inliner.js:105:13)
```
