### ISSUE TITLE
-webkit-image-set() error

### ISSUE THREAD

**Issue by yisibl** [jakubpawlowicz/clean-css#650] opened 2015-08-18 06:54 UTC
input:

```css
.foo {
  background: url(foo.png) 50% 0 no-repeat; /* fallback */
  background: -webkit-image-set(url(foo.png) 1x,
                                url(foo-2x.png) 2x) 50% 0 no-repeat;
}
```

output:
```css
.foo{background:50% 0 no-repeat}
```

This is a very serious problem, and the result is completely wrong.

**Comment by jakubpawlowicz** [comment] 2015-08-18 06:57
Duplicate of #618, already fixed on master.

**Closed by jakubpawlowicz** 2015-08-18 06:57 UTC

**Comment by yisibl** [comment] 2015-08-18 07:01
Thank you very much, I hope to release as soon as possible.

**Comment by jakubpawlowicz** [comment] 2015-08-18 07:03
3.4 should be out this week, in the meantime you have to skip advanced processing.
