### ISSUE TITLE
Minification process replacing absolute units with px

### ISSUE THREAD

**Issue by renatogcarvalho** [jakubpawlowicz/clean-css#672] opened 2015-09-16 05:36 UTC
Hello guys,

I'm running into an issue that started happening in one of your latest releases - not exactly sure what is the build number, please accept my apologies.

During the deployment of one of the applications at my workplace we noticed that "gulp-minify-css" (which basically a wrapper for "clean-css") is currently replacing absolute units (pc, pt, etc) with px.

Although this seems to be not affecting the layout of our pages on Google Chrome, Firefox and Safari, it is completely breaking the layout on Internet Explorer (9 and above). The only way I was able to avoid these units to be replaced was setting the "advanced" option to false. Although I don't think this is the best solution, this issue was affecting our deployments on production and we really needed to find a way around it. 

Do you have any ideas on why this is happening? Could you please tell us if there is a cleaner way to avoid this behavior?

Thank you in advance.

Renato.

**Comment by jakubpawlowicz** [comment] 2015-09-16 05:39
It's a duplicate of #654 - fixed in version 3.4.2 and up. You could probably just delete gulp plugin from `node_modules` and rerun the build so it uses the latest clean-css.

**Closed by jakubpawlowicz** 2015-09-16 05:39 UTC

**Comment by renatogcarvalho** [comment] 2015-09-16 05:43
Hello @jakubpawlowicz,

I actually looked at this issue earlier today and did exactly what you just described above.

However, for some reason it still didn't work as expected... I was wondering if the fix was also going to be applied the other way around, absolute units to px. 

I'll give it another whirl once I get on my workplace tomorrow though.

Much appreciated.

Renato.

**Comment by jakubpawlowicz** [comment] 2015-09-16 05:48
All the units are kept unchanged now, so there's no absolute units -> px conversion.

If you have access to the server then `npm ls clean-css` will help you find out what version of clean-css you are using and where it's located.

Hope this helps.

**Comment by renatogcarvalho** [comment] 2015-09-16 05:57
Below you can find the output I'm currently getting:

renato@server:/path$ npm ls clean-css
project.com@1.0.0 /path
âââ¬ gulp-minify-css@1.2.1
  âââ clean-css@3.4.3

It looks like we're using the right version according to what you mentioned on your first reply (3.4.2+).

Any thoughts? Would you like me to send you an example of what the output looks like before and after we noticed the issue?

Renato.

**Comment by jakubpawlowicz** [comment] 2015-09-16 06:17
You certainly have the right version. I would make sure you serve the updated files, they are not cached on the server or in a browser in the first place.
