### ISSUE TITLE
Merge media queries

### ISSUE THREAD

**Issue by XhmikosR** [jakubpawlowicz/clean-css#204] opened 2014-01-03 12:12 UTC
When dealing with multiple CSS files and media queries, merging those would improve compression a lot.

**Comment by jakubpawlowicz** [comment] 2015-01-29 22:59
As far as I can see a `@media` can't be moved, thus merged, if any of its selectors or properties is being redefined in between, as specificity is the same and only order matters, e.g.

```css
@media (min-width: 1024px) {
  .one { background: red }
  .two { color: blue }
}
.two { color: red }
@media (min-width: 1024px) {
  .one { color: red; display: block }
}
```

Tricky.

**Comment by XhmikosR** [comment] 2015-01-30 09:03
@jakubpawlowicz: you are right about that case. But all others should be OK to merge. Maybe looking at https://github.com/buildingblocks/grunt-combine-media-queries/blob/master/tasks/combine-media-queries.js can help.

**Comment by jakubpawlowicz** [comment] 2015-01-30 09:44
:+1: will do!

**Comment by jakubpawlowicz** [comment] 2015-02-10 09:10
Please feel free to give `204-media-merging` branch a try - should work well.

**Comment by XhmikosR** [comment] 2015-02-10 09:16
@jakubpawlowicz: I see a regression

```css
.btn-group>.btn:not(:first-child):not(:last-child):not(.dropdown-toggle){border-radius:0}
```

```css
.btn-group>.btn:not(:first-child) :not(:last-child) :not(.dropdown-toggle){border-radius:0}
```

**Comment by jakubpawlowicz** [comment] 2015-02-10 09:17
Good catch :+1:

**Comment by XhmikosR** [comment] 2015-02-10 09:18
Also, the current implementation won't be very useful... I mean, it only merges media queries that are one after another, which isn't usually the case... I mean, try this branch with the css minification benchmark data.

**Comment by jakubpawlowicz** [comment] 2015-02-10 11:00
In fact it does already, see:
https://github.com/jakubpawlowicz/clean-css/blob/204-media-merging/lib/selectors/optimizers/advanced.js#L422
https://github.com/jakubpawlowicz/clean-css/blob/204-media-merging/test/media-queries-test.js#L34

It is not always possible since any selectors in between may redefine content. It's not perfect but we are moving there.

**Comment by jakubpawlowicz** [comment] 2015-02-10 15:54
@XhmikosR Regression fixed.

**Comment by XhmikosR** [comment] 2015-02-10 16:33
Cool, but still no real gain in Bootstrap for example. :/

**Comment by jakubpawlowicz** [comment] 2015-02-10 16:42
Feel free to point to underoptimized parts of CSS in bootstrap and I'll take a look.

**Comment by XhmikosR** [comment] 2015-02-10 16:43
I mean, none of the current media queries seems to get merged with the current 204-media-merging branch.

**Comment by jakubpawlowicz** [comment] 2015-02-10 16:52
That's odd, I can see some improvements:

```shell
-rw-r--r--  1 jakub  staff  113245 Feb 10 16:45 /Users/jakub/Desktop/bootstrap-old.min.css
-rw-r--r--  1 jakub  staff  112638 Feb 10 16:45 /Users/jakub/Desktop/bootstrap.min.css
```

**Comment by XhmikosR** [comment] 2015-02-10 16:53
Those come from the spaces in media queries being removed as far as I can tell.

**Comment by jakubpawlowicz** [comment] 2015-02-10 16:57
Not really - that's 3.0 branch, master, and media merging:

```shell
-rw-r--r--  1 jakub  staff  113386 Feb 10 16:54 /Users/jakub/Desktop/bootstrap-3.0.min.css
-rw-r--r--  1 jakub  staff  113245 Feb 10 16:45 /Users/jakub/Desktop/bootstrap-master.min.css
-rw-r--r--  1 jakub  staff  112638 Feb 10 16:45 /Users/jakub/Desktop/bootstrap-media.min.css
```

**Comment by XhmikosR** [comment] 2015-02-10 17:10
Maybe a few are merged; comparing was done very quickly since I don't have keep line breaks enabled for production ;)

Anyway, another issue with this branch and the css minification benchmark


```
C:\Users\xmr\Desktop\css-minification-benchmark>npm run bench

> css-minification-benchmark@1.0.0 bench C:\Users\xmr\Desktop\css-minification-benchmark
> node ./bin/bench --html>index.html

......................[Error: SyntaxError: missing ) line 1 col 5185 look ,]
...........................F......................................F.............
......................................................
```

Using 3.0.10 doesn't give any errors.

**Closed** 2015-02-11 09:04 UTC
Labels: Enhancement
