### ISSUE TITLE
A,B,C layout disabling ?

### ISSUE THREAD

**Issue by erkanunluturk** [jakubpawlowicz/clean-css#515] opened 2015-04-06 23:05 UTC
stylus file:

```stylus
.b
.c
.a
.d
	margin 0
```

output file:

```css
.a,.b,.c,.d{margin:0}

```

**Comment by jakubpawlowicz** [comment] 2015-04-08 07:35
Duplicate of #425.

**Closed by jakubpawlowicz** 2015-04-08 07:35 UTC
