### ISSUE TITLE
background: linear-gradient, white combined with transparent, turns into black shadow

### ISSUE THREAD

**Issue by boocL** [jakubpawlowicz/clean-css#762] opened 2016-04-23 12:42 UTC
Runnnig this piece of css with version 3.4.12 (or an older version) on the CLI OS X 10.11

    .fading-line {
      background: -moz-linear-gradient    (top,rgba(255,255,255,1) 80%,       rgba(255,255,255,0) 100%); /* FF3.6+ */  
      background: -webkit-linear-gradient (top,rgba(255,255,255,1) 80%,       rgba(255,255,255,0) 100%); /* Chrome10+,Safari5.1+ */  
      background: linear-gradient         (to bottom,rgba(255,255,255,1) 80%, rgba(255,255,255,0) 100%); /* W3C */  
    }

Creates and output with `transparent 100%` and not `rgba(255,255,255,0) 100%`

    .fading-line{
      background:-moz-linear-gradient    (top,rgba(255,255,255,1) 80%,       transparent 100%);
      background:-webkit-linear-gradient (top,rgba(255,255,255,1) 80%,       transparent 100%);
      background:linear-gradient         (to bottom,rgba(255,255,255,1) 80%, transparent 100%)
    }

My white to transparent `span`, turns into white with a black shadow `span`.
More complete example created with http://colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&1+0,1+80,0+100 results in the same issue.

OS X 10.11
Spaces in the output are added manualy to make it more readable.

**Comment by jakubpawlowicz** [comment] 2016-04-24 08:48
We had a similar issue before to keep transparency in gradients, but I can see it happening here. Let's fix it!

**Comment by jakubpawlowicz** [comment] 2016-05-29 15:17
Strangely I can't reproduce it under 3.4.13. Closing but please reopen if still happens.

**Closed by jakubpawlowicz** 2016-05-29 15:17 UTC
Labels: Bug
