### ISSUE TITLE
Having a non-breaking space in css leads to error

### ISSUE THREAD

**Issue by blackholegalaxy** [jakubpawlowicz/clean-css#1006] opened 2018-02-20 00:01 UTC
### Environment

Using clean-css through Angular CLI 1.7.0 which moved to clean-css. clean-css is imported through webpack plugin as it can seen here: https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/plugins/cleancss-webpack-plugin.ts

### Configuration options

```js
 const cleancss = new CleanCSS({
          compatibility: 'ie9',
          level: 2,
          inline: false,
          returnPromise: true,
          sourceMap: this._options.sourceMap,
        });
```

### Input SCSS

Image, since non-breaking space would not show up properly (screenshot taken on VSCode on faulty scss code, with Highlight bad characters VSCode plugin):

![bad_char](https://user-images.githubusercontent.com/11064123/36401689-10bf3cc0-15a7-11e8-892d-10d2b93e9e48.PNG)

This code was transpiled to CSS, which still contains the non-breaking space. Resulting in following error.

### Error

> /project/node_modules/clean-css/lib/reader/input-source-map-tracker.js:37
>   if (originalPosition.line === null && line > 1 && selectorFallbacks > 0) {
> 
> TypeError: Cannot read property 'line' of undefined
>     at originalPositionFor (/project/node_modules/clean-css/lib/reader/input-source-map-tracker.js:37:24)
>     at originalMetadata (/project/node_modules/clean-css/lib/tokenizer/tokenize.js:486:43)
>     at intoTokens (/project/node_modules/clean-css/lib/tokenizer/tokenize.js:435:68)
>     at tokenize (/project/node_modules/clean-css/lib/tokenizer/tokenize.js:74:10)
>     at fromStyles (/project/node_modules/clean-css/lib/reader/read-sources.js:147:12)
>     at fromString (/project/node_modules/clean-css/lib/reader/read-sources.js:48:10)
>     at doReadSources (/project/node_modules/clean-css/lib/reader/read-sources.js:33:12)
>     at readSources (/project/node_modules/clean-css/lib/reader/read-sources.js:24:10)
>     at /project/node_modules/clean-css/lib/clean.js:99:12
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

### Expected behavior

Presence of non-breaking space should not block the production of css since these kind of spaces should be deleted in the minification process.

### Potential fix

We could add a marker for no-break space and replace the character with standard space.

```
NO_BREAK_SPACE: /\u00A0|\u202F|\uFEFF/g,
```

then in tokenize:
```
isNoBreakSpace = Marker.NO_BREAK_SPACE.test(character);
...
else if (isNoBreakSpace) {
      // Replace any kind of no-break-space with standard space
      character = Marker.SPACE;
      buffer.push(character);
    }
```

Can't open a PR as I don't know how to test that in your test suit.

**Comment by jotapsl** [comment] 2018-02-20 15:31
+1

**Comment by tx8821** [comment] 2018-02-27 11:42
Please fix this! Angular CLI cant build because of this!

**Comment by FirassKoubaa** [comment] 2018-02-28 15:31
+1

**Comment by renatomrcosta** [comment] 2018-03-01 11:32
+1

**Comment by barocsi** [comment] 2018-03-01 14:45
+1 this is so funny in a sad way.

**Comment by scote** [comment] 2018-03-02 03:08
Any new when it will be fixed?

**Comment by markgoho-EDT** [comment] 2018-03-02 22:19
@jakubpawlowicz are any contributors able to help with this issue?

**Comment by vithubati** [comment] 2018-03-03 00:08
any update on this?

**Comment by barocsi** [comment] 2018-03-03 00:11
if it helps just scan all of your files for non breaking space using Notepad++ or regex in IntelliJ / VS whichever tool you use to spot bad chars.
regex this:
```
\xA0
```

**Comment by blackholegalaxy** [comment] 2018-03-03 00:28
I gave a code snippet on the main issue post. By patching clean-css with it it works properly. The fact is I don't know how to write test on clean-css context, so I can't open a PR.

**Comment by scote** [comment] 2018-03-03 02:57
@barocsi for me the error came from a third party lib (materialize-css) i'm using in my project.

**Comment by jakubpawlowicz** [comment] 2018-03-05 09:59
Sure, will fix it in 4.1.10 coming out (hopefully) today.

**Comment by jakubpawlowicz** [comment] 2018-03-05 11:07
Hmmm, I took a look at the source code and we read all files as utf-8 not utf-16, so it will be rather tricky to fix at this point. Could you at least provide me with a test CSS file to test on?

**Comment by enavarro222** [comment] 2018-03-05 11:34
@jakubpawlowicz the issue appears with materializecss (tested with v0.100.2) cf https://github.com/Dogfalo/materialize/blob/master/dist/css/materialize.min.css

btw, as mention by @scote, as this issue is raised by a third party lib, this is really annoying ! I hope you could find a solution quickly... Thank you very much to address this issue !

**Comment by jakubpawlowicz** [comment] 2018-03-05 11:49
Thanks @enavarro222 for a quick reply. I've fetched the file but can't replicate the issue yet - since the it shows up when reading input source maps, can someone please post materialize.css transpiled from SCSS **with** source map?

**Comment by enavarro222** [comment] 2018-03-05 14:14
@jakubpawlowicz not sure is it could help but here is a minimal setup to reproduce the issue with angular cli :
```
$ npm install -g @angular/cli
$ ng new testproject
$ cd testproject
$ npm install materialize-css
```
Then you have to add `materialize.min.css` in `.angular-cli.json`:
```
...
      "styles": [
        "styles.css",
        "../node_modules/materialize-css/dist/css/materialize.min.css"
      ],
...
```
And then:
```
$ ng build --prod
 92% chunk asset optimization/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/reader/input-source-map-tracker.js:37
  if (originalPosition.line === null && line > 1 && selectorFallbacks > 0) {
                      ^

TypeError: Cannot read property 'line' of undefined
    at originalPositionFor (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/reader/input-source-map-tracker.js:37:23)
    at originalMetadata (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/tokenizer/tokenize.js:486:43)
    at intoTokens (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/tokenizer/tokenize.js:435:68)
    at tokenize (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/tokenizer/tokenize.js:74:10)
    at fromStyles (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/reader/read-sources.js:147:12)
    at fromString (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/reader/read-sources.js:48:10)
    at doReadSources (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/reader/read-sources.js:33:12)
    at readSources (/Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/reader/read-sources.js:24:10)
    at /Users/navarro/workspace/tmp/testproject/node_modules/clean-css/lib/clean.js:99:12
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by scote** [comment] 2018-03-05 14:16
@angular/cli version must be greater `1.6.8`.

**Comment by blackholegalaxy** [comment] 2018-03-05 16:50
@enavarro222  thx for repro. 

You could also simply add any no breaking space anywhere in any css. It will break.Here is the character: " " (reference: http://www.fileformat.info/info/unicode/char/00a0/browsertest.htm)

This character exists in UTF-8 @jakubpawlowicz 

The error occurs when any of the three kind of no-break space is present:
```
\u00A0
\u202F
\uFEFF
```

**Comment by jakubpawlowicz** [comment] 2018-03-05 17:20
I've been able to reproduce the issue locally, however it's not entirely clean-css bug but also sass building incorrect source map. I found couple cases when line:column data inside it is invalid (e.g. column being negative causing `source-map` to explode when verifying it).

However I'll add some code to handle such cases gracefully.

**Comment by blackholegalaxy** [comment] 2018-03-05 17:30
Great! Thanks @jakubpawlowicz

**Comment by jakubpawlowicz** [comment] 2018-03-05 18:38
It's fixed in 4.1.10.

**Closed** 2018-03-05 18:37 UTC
Labels: bug, more details needed

**Comment by scote** [comment] 2018-03-05 18:42
@blackholegalaxy will you reopen your issue on angular/cli?

**Comment by renatomrcosta** [comment] 2018-03-05 19:07
Great work @jakubpawlowicz! Thanks!

**Comment by blackholegalaxy** [comment] 2018-03-05 21:07
@cote since it will be fixed by version 4.1.10 here angular CLI issue should solve by itself since they have a dependency set to `"clean-css": "^4.1.9",`

**Comment by blackholegalaxy** [comment] 2018-03-05 21:25
Just a quick real project test with invalid char on scss source. Removed node_modules and let npm install latest clean-css. Tested under 1.6.8, 1.7.0, 1.7.1, 1.7.2:

![works](https://user-images.githubusercontent.com/11064123/37000544-c0ffdece-2091-11e8-9995-8afd813a5168.PNG)

**Comment by jakubpawlowicz** [comment] 2018-03-06 06:10
Boom, cheers! :beer:

**Comment by enavarro222** [comment] 2018-03-06 09:17
thanks a lot @jakubpawlowicz  !
