### ISSUE TITLE
Output ends with __ESCAPED_SOURCE_END_CLEAN_CSS__

### ISSUE THREAD

**Issue by davewallace** [jakubpawlowicz/clean-css#789] opened 2016-06-21 04:43 UTC
I have a vendor-provided CSS file which I am using `grunt-contrib-cssmin` (^1.0.1) to strip out comments and minify.

The file is processed, and the output ends with `__ESCAPED_SOURCE_END_CLEAN_CSS__`.

A sample of the vendor file I am processing is attached (had to change file ext. to `.txt` so it would upload, but I am dealing with the same file with ext. `.css`).

Is there anything in this sample file that would cause the processing to add this output?

Cheers :D
[player.txt](https://github.com/jakubpawlowicz/clean-css/files/324801/player.txt)

**Comment by jakubpawlowicz** [comment] 2016-06-21 10:02
I can see (with a hex editor) that this file ends with 0x1a character which seems to be a Windows Ctrl-Z control code. Quick fix is just to remove it but it'd be good to find out why it results in such behavior.

http://stackoverflow.com/questions/17024436/what-is-the-unicode-u001a-character-aka-0x1a

**Comment by davewallace** [comment] 2016-06-21 21:38
True, it does, and that char is also added during processing. It's less of a concern than the `__ESCAPED_SOURCE_END_CLEAN_CSS__` that is also inserted however.

**Comment by jakubpawlowicz** [comment] 2016-12-19 06:54
Thanks to the new tokenizer this is no longer an issue. Added a test case and marking it as fixed on master. Thanks @davewallace!

**Closed by jakubpawlowicz** 2016-12-19 06:54 UTC
Labels: Enhancement

**Comment by brooksreese** [comment] 2016-12-19 21:30
@davewallace I just reproduced the error and it seems to only happen on css files with errors.  For example, if you add body { background-color: orange; } in one file, then misspell background in another file, the second file would have __ESCAPED_SOURCE_END_CLEAN_CSS__ added to the end.  Is this the same behavior happening on your system?

**Comment by davewallace** [comment] 2016-12-20 00:25
For my part, I was dealing with vendor contributed files which we did not want to touch anyway, so whether it was a parsing error which resulted in the `__ESCAPED_SOURCE_END_CLEAN_CSS__ ` or not, the point is moot as we wouldn't change a given error to avoid the problem apparent in this issue.

Thinking back though, I seem to recall removing some comments via minification which removed the error... this is a while ago for me now, done a lot of things since, so I may be incorrect there.
