### ISSUE TITLE
css calc height fallback for older browsers

### ISSUE THREAD

**Issue by Ghostavio** [jakubpawlowicz/clean-css#591] opened 2015-06-02 11:19 UTC
Hello, so I'm using the following in my code:
```
height: 100%;
height: calc(100% - 55px);
```
So for browsers without `calc` support, the first value should be taken, but cssmin is removing it and keeping just `height: calc(100% - 55px);`, there's anyway to keep this particular duplicated css attribute without disabling all the duplication removal, or maybe creating a rule for this specific case?
In case it's not possible, how would I completely disable the check for duplication?

Thanks.

**Comment by jakubpawlowicz** [comment] 2015-06-02 20:14
Could you share your cssmin setup? I can clearly see it works fine in any 3.x:

```bash
> echo "a{height:100%;height:calc(100% - 55px)}" | ./bin/cleancss
a{height:100%;height:calc(100% - 55px)}
```

**Comment by jakubpawlowicz** [comment] 2015-06-08 06:30
I'll close it for now, but please reopen if needed.

**Closed by jakubpawlowicz** 2015-06-08 06:30 UTC

**Comment by ahmedelgabri** [comment] 2015-11-09 10:02
@jakubpawlowicz I have the same exact issue and here is how you can reproduce the problem.

This looks fine
```sh
 $ echo ".foo { display: block; display: flex; color: green; align-items: center; }" | ./node_modules/.bin/cleancss
.foo{display:block;display:flex;color:green;align-items:center}
```

This is not, **I moved `color` between the two display declarations**
```sh
$ echo ".foo { display: block; color: green; display: flex; align-items: center; }" | ./node_modules/.bin/cleancss
.foo{color:green;display:flex;align-items:center}
```

It's very subtle but developers will expect their code to work the same in both situations. For now `advanced: false` fixes this but I think that this behaviour should be normalized. Not sure how since it's a very hard problem to determine when it's a fallback and when it's a duplicated declaration.

**Comment by jakubpawlowicz** [comment] 2015-11-23 20:46
@ahmedelgabri you can also use `aggressiveMerging: false` for the same effect. Solving this is dependent on #290.

**Comment by ahmedelgabri** [comment] 2015-11-24 10:55
Thanks @jakubpawlowicz
