### ISSUE TITLE
Not recognizing border shorthand / longhand notations as expected with pseudo classes

### ISSUE THREAD

**Issue by michaelerobertsjr** [jakubpawlowicz/clean-css#622] opened 2015-07-20 21:10 UTC
Here is a link to our relevant CSS:
https://gist.github.com/michaelerobertsjr/a6e0408f843380f2c3f5

When we do a diff of the final output using minified vs not minified less builds we've noticed that the order of the pseudo classes and grouping is not done the way we expected (minified on the right):
![diff](https://cloud.githubusercontent.com/assets/4172887/8787207/ae46b5d0-2ee7-11e5-9310-2da2baf31807.png)

Minification places the :before then the :after with :before, and then :after, which causes border to be overwritten in this use case.

This also seemed to appear recently, and we did not notice this issue prior to last week.  We suspect a recent change to the code base is causing this issue.

**Comment by michaelerobertsjr** [comment] 2015-07-20 21:53
We have discovered a couple of things.  1) This probably was not a recent change, but it may have occurred further back and we just did not notice the change when gulp-minify was updated to use the latest clean-css.

We can turn off restructure and it fixes this issue, but it results in a much larger file size. Aprox 50% file size increase with restructure:false.

**Comment by jakubpawlowicz** [comment] 2015-07-22 07:31
@michaelerobertsjr This is a duplicate of #616 - stay tuned for a fix I'm working on.

**Closed by jakubpawlowicz** 2015-07-22 07:31 UTC
