### ISSUE TITLE
--s1 fails when using --source-map

### ISSUE THREAD

**Issue by shinnn** [jakubpawlowicz/clean-css#549] opened 2015-04-24 22:59 UTC
### Fixtures

in-with-map.css:

```css
/*!
comment 1
*/a{color:#00f}/*!
comment 2
*/b{color:red}/*!
comment 3
*/i{color:green}/*# sourceMappingURL=in-with-map.css.map */
```

in-with-map.css.map:

```json
{"version":3,"sources":["source.css"],"names":[],"mappings":";;AAGA,EACI,MAAO;;AAMX,EACI,MAAO;;AAMX,EACI,MAAO"}
```

### Versions

```
$ node -v
v1.8.1
$ npm -v
2.8.3
$ cleancss -v
3.2.4
```

### 1. without --source-map (OK)

```
$ cleancss --s1 -o out.css in-with-map.css
```

out.css:

```css
/*!
comment 1
*/a{color:#00f}b{color:red}i{color:green}
```

(works as expected)

### 2. with --source-map (not OK)

```
$ cleancss --s1 --source-map -o out.css in-with-map.css
```

out.css:

```css
/*!
comment 1
*/a{color:#00f}/*!
comment 2
*/b{color:red}/*!
comment 3
*/i{color:green}/*# sourceMappingURL=out.css.map */
```

(still contains too many comments despite `--s1` flag)

**Comment by AlexanderOMara** [comment] 2015-04-25 01:21
@shinnn Thanks for opening this issue, and reproducing it in just clean-css. I think I've narrowed down what's causing the issue.

In `lib/stringifier/simple.js`, the restore function [is called once](https://github.com/jakubpawlowicz/clean-css/blob/8eb2ac659de59690552c1436e28400cd3a561a27/lib/text/comments-processor.js#L97-L125). However, in `lib/stringifier/source-maps.js` the restore function [is called multiple times](https://github.com/jakubpawlowicz/clean-css/blob/8b79c916905758130df58e050077e8ee9754e182/lib/stringifier/source-maps.js#L12).

Because of this, the counter in the `lib/text/comments-processor.js` [`restore` function](https://github.com/jakubpawlowicz/clean-css/blob/8eb2ac659de59690552c1436e28400cd3a561a27/lib/text/comments-processor.js#L97-L125) fails to keep track.

Of course, simple moving the function to the end breaks the source maps, so I'm not sure what the cleanest solution to this would be.

**Comment by jakubpawlowicz** [comment] 2015-04-25 08:44
Thanks @shinnn for outstanding bug report and @AlexanderOMara for pointing me into the right spot. It's fixed in 3.2.5 now.

**Closed** 2015-04-25 08:43 UTC

**Comment by shinnn** [comment] 2015-04-25 08:48
@jakubpawlowicz You're welcome. Thanks for the new release!

**Comment by jakubpawlowicz** [comment] 2015-04-25 08:52
Cheers!

**Comment by AlexanderOMara** [comment] 2015-04-25 16:08
Awesome! Thanks for the quick fix!
